/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyReviewRouteImport } from './routes/weekly-review'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RecurrenceRouteImport } from './routes/recurrence'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OpenLoopsRouteImport } from './routes/open-loops'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsHealthRouteImport } from './routes/projects.health'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as OpenLoopsIdRouteImport } from './routes/open-loops.$id'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'
import { Route as DebugTelemetryRouteImport } from './routes/debug.telemetry'
import { Route as DebugAnalyticsRouteImport } from './routes/debug.analytics'
import { Route as ActionsIdRouteImport } from './routes/actions.$id'

const WeeklyReviewRoute = WeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrenceRoute = RecurrenceRouteImport.update({
  id: '/recurrence',
  path: '/recurrence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenLoopsRoute = OpenLoopsRouteImport.update({
  id: '/open-loops',
  path: '/open-loops',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHealthRoute = ProjectsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const OpenLoopsIdRoute = OpenLoopsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpenLoopsRoute,
} as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IdeasRoute,
} as any)
const DebugTelemetryRoute = DebugTelemetryRouteImport.update({
  id: '/debug/telemetry',
  path: '/debug/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAnalyticsRoute = DebugAnalyticsRouteImport.update({
  id: '/debug/analytics',
  path: '/debug/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsIdRoute = ActionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/ask': typeof AskRoute
  '/attention': typeof AttentionRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/open-loops': typeof OpenLoopsRouteWithChildren
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recurrence': typeof RecurrenceRoute
  '/review': typeof ReviewRoute
  '/weekly-review': typeof WeeklyReviewRoute
  '/actions/$id': typeof ActionsIdRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/debug/telemetry': typeof DebugTelemetryRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/open-loops/$id': typeof OpenLoopsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/health': typeof ProjectsHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/ask': typeof AskRoute
  '/attention': typeof AttentionRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/open-loops': typeof OpenLoopsRouteWithChildren
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recurrence': typeof RecurrenceRoute
  '/review': typeof ReviewRoute
  '/weekly-review': typeof WeeklyReviewRoute
  '/actions/$id': typeof ActionsIdRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/debug/telemetry': typeof DebugTelemetryRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/open-loops/$id': typeof OpenLoopsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/health': typeof ProjectsHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRouteWithChildren
  '/activity': typeof ActivityRoute
  '/ask': typeof AskRoute
  '/attention': typeof AttentionRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/open-loops': typeof OpenLoopsRouteWithChildren
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/recurrence': typeof RecurrenceRoute
  '/review': typeof ReviewRoute
  '/weekly-review': typeof WeeklyReviewRoute
  '/actions/$id': typeof ActionsIdRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/debug/telemetry': typeof DebugTelemetryRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/open-loops/$id': typeof OpenLoopsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/health': typeof ProjectsHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/activity'
    | '/ask'
    | '/attention'
    | '/ideas'
    | '/open-loops'
    | '/overview'
    | '/projects'
    | '/recurrence'
    | '/review'
    | '/weekly-review'
    | '/actions/$id'
    | '/debug/analytics'
    | '/debug/telemetry'
    | '/ideas/$id'
    | '/open-loops/$id'
    | '/projects/$id'
    | '/projects/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/activity'
    | '/ask'
    | '/attention'
    | '/ideas'
    | '/open-loops'
    | '/overview'
    | '/projects'
    | '/recurrence'
    | '/review'
    | '/weekly-review'
    | '/actions/$id'
    | '/debug/analytics'
    | '/debug/telemetry'
    | '/ideas/$id'
    | '/open-loops/$id'
    | '/projects/$id'
    | '/projects/health'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/activity'
    | '/ask'
    | '/attention'
    | '/ideas'
    | '/open-loops'
    | '/overview'
    | '/projects'
    | '/recurrence'
    | '/review'
    | '/weekly-review'
    | '/actions/$id'
    | '/debug/analytics'
    | '/debug/telemetry'
    | '/ideas/$id'
    | '/open-loops/$id'
    | '/projects/$id'
    | '/projects/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AskRoute: typeof AskRoute
  AttentionRoute: typeof AttentionRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  OpenLoopsRoute: typeof OpenLoopsRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RecurrenceRoute: typeof RecurrenceRoute
  ReviewRoute: typeof ReviewRoute
  WeeklyReviewRoute: typeof WeeklyReviewRoute
  DebugAnalyticsRoute: typeof DebugAnalyticsRoute
  DebugTelemetryRoute: typeof DebugTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-review': {
      id: '/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof WeeklyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrence': {
      id: '/recurrence'
      path: '/recurrence'
      fullPath: '/recurrence'
      preLoaderRoute: typeof RecurrenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-loops': {
      id: '/open-loops'
      path: '/open-loops'
      fullPath: '/open-loops'
      preLoaderRoute: typeof OpenLoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/health': {
      id: '/projects/health'
      path: '/health'
      fullPath: '/projects/health'
      preLoaderRoute: typeof ProjectsHealthRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/open-loops/$id': {
      id: '/open-loops/$id'
      path: '/$id'
      fullPath: '/open-loops/$id'
      preLoaderRoute: typeof OpenLoopsIdRouteImport
      parentRoute: typeof OpenLoopsRoute
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/debug/telemetry': {
      id: '/debug/telemetry'
      path: '/debug/telemetry'
      fullPath: '/debug/telemetry'
      preLoaderRoute: typeof DebugTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/analytics': {
      id: '/debug/analytics'
      path: '/debug/analytics'
      fullPath: '/debug/analytics'
      preLoaderRoute: typeof DebugAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions/$id': {
      id: '/actions/$id'
      path: '/$id'
      fullPath: '/actions/$id'
      preLoaderRoute: typeof ActionsIdRouteImport
      parentRoute: typeof ActionsRoute
    }
  }
}

interface ActionsRouteChildren {
  ActionsIdRoute: typeof ActionsIdRoute
}

const ActionsRouteChildren: ActionsRouteChildren = {
  ActionsIdRoute: ActionsIdRoute,
}

const ActionsRouteWithChildren =
  ActionsRoute._addFileChildren(ActionsRouteChildren)

interface IdeasRouteChildren {
  IdeasIdRoute: typeof IdeasIdRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdRoute: IdeasIdRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

interface OpenLoopsRouteChildren {
  OpenLoopsIdRoute: typeof OpenLoopsIdRoute
}

const OpenLoopsRouteChildren: OpenLoopsRouteChildren = {
  OpenLoopsIdRoute: OpenLoopsIdRoute,
}

const OpenLoopsRouteWithChildren = OpenLoopsRoute._addFileChildren(
  OpenLoopsRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsHealthRoute: typeof ProjectsHealthRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsHealthRoute: ProjectsHealthRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AskRoute: AskRoute,
  AttentionRoute: AttentionRoute,
  IdeasRoute: IdeasRouteWithChildren,
  OpenLoopsRoute: OpenLoopsRouteWithChildren,
  OverviewRoute: OverviewRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RecurrenceRoute: RecurrenceRoute,
  ReviewRoute: ReviewRoute,
  WeeklyReviewRoute: WeeklyReviewRoute,
  DebugAnalyticsRoute: DebugAnalyticsRoute,
  DebugTelemetryRoute: DebugTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
