/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as GlanceRouteImport } from './routes/glance'
import { Route as CaptureDoctorRouteImport } from './routes/capture-doctor'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'
import { Route as DebugAnalyticsRouteImport } from './routes/debug.analytics'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const GlanceRoute = GlanceRouteImport.update({
  id: '/glance',
  path: '/glance',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureDoctorRoute = CaptureDoctorRouteImport.update({
  id: '/capture-doctor',
  path: '/capture-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IdeasRoute,
} as any)
const DebugAnalyticsRoute = DebugAnalyticsRouteImport.update({
  id: '/debug/analytics',
  path: '/debug/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/attention': typeof AttentionRoute
  '/capture-doctor': typeof CaptureDoctorRoute
  '/glance': typeof GlanceRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/attention': typeof AttentionRoute
  '/capture-doctor': typeof CaptureDoctorRoute
  '/glance': typeof GlanceRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/attention': typeof AttentionRoute
  '/capture-doctor': typeof CaptureDoctorRoute
  '/glance': typeof GlanceRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/screens': typeof ScreensRoute
  '/settings': typeof SettingsRoute
  '/debug/analytics': typeof DebugAnalyticsRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/attention'
    | '/capture-doctor'
    | '/glance'
    | '/ideas'
    | '/login'
    | '/overview'
    | '/projects'
    | '/screens'
    | '/settings'
    | '/debug/analytics'
    | '/ideas/$id'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/attention'
    | '/capture-doctor'
    | '/glance'
    | '/ideas'
    | '/login'
    | '/overview'
    | '/projects'
    | '/screens'
    | '/settings'
    | '/debug/analytics'
    | '/ideas/$id'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/attention'
    | '/capture-doctor'
    | '/glance'
    | '/ideas'
    | '/login'
    | '/overview'
    | '/projects'
    | '/screens'
    | '/settings'
    | '/debug/analytics'
    | '/ideas/$id'
    | '/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AttentionRoute: typeof AttentionRoute
  CaptureDoctorRoute: typeof CaptureDoctorRoute
  GlanceRoute: typeof GlanceRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ScreensRoute: typeof ScreensRoute
  SettingsRoute: typeof SettingsRoute
  DebugAnalyticsRoute: typeof DebugAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glance': {
      id: '/glance'
      path: '/glance'
      fullPath: '/glance'
      preLoaderRoute: typeof GlanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-doctor': {
      id: '/capture-doctor'
      path: '/capture-doctor'
      fullPath: '/capture-doctor'
      preLoaderRoute: typeof CaptureDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/debug/analytics': {
      id: '/debug/analytics'
      path: '/debug/analytics'
      fullPath: '/debug/analytics'
      preLoaderRoute: typeof DebugAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IdeasRouteChildren {
  IdeasIdRoute: typeof IdeasIdRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdRoute: IdeasIdRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AttentionRoute: AttentionRoute,
  CaptureDoctorRoute: CaptureDoctorRoute,
  GlanceRoute: GlanceRoute,
  IdeasRoute: IdeasRouteWithChildren,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ScreensRoute: ScreensRoute,
  SettingsRoute: SettingsRoute,
  DebugAnalyticsRoute: DebugAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
